In [1]:
import pandas as pd 
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC


In [2]:
data = load_iris()

In [3]:
dir(data)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [4]:
df = pd.DataFrame(data.data,columns=data.feature_names)

In [5]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
df['target'] = data.target

In [7]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [8]:
X = df.drop('target',axis=1)

In [9]:
y = df.target

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [11]:
X_train.shape

(120, 4)

In [12]:
X_test.shape

(30, 4)

In [13]:
model = SVC()

In [14]:
model.fit(X_train,y_train)

SVC()

In [15]:
model.score(X_test,y_test)

1.0

In [16]:
model = SVC()
model.fit(X_train,y_train)
model.score(X_test,y_test)

1.0

In [17]:
from sklearn.model_selection import cross_val_score

In [20]:
cross_val_score(SVC(C=1.0,kernel='rbf',gamma='scale'),X,y,cv=3)

array([0.96, 0.98, 0.94])

In [21]:
cross_val_score(SVC(C=1.0,kernel='linear',gamma='scale'),X,y,cv=3)

array([1.  , 1.  , 0.98])

In [22]:
cross_val_score(SVC(C=10.0,kernel='rbf'),X,y,cv=3)

array([0.98, 1.  , 0.94])

In [24]:
cross_val_score(SVC(C=10.0,kernel='poly',degree=2),X,y,cv=3)

array([0.98, 0.94, 0.98])

In [25]:
kval = ['rbf','linear']
cval = [1,10,20]

In [27]:
for i in kval :
    for j in cval:
        print(cross_val_score(SVC(C=j,kernel=i,gamma='scale'),X,y,cv=3))
        

[0.96 0.98 0.94]
[0.98 1.   0.94]
[0.98 0.98 0.98]
[1.   1.   0.98]
[1.   0.94 0.98]
[1.   0.94 0.96]


In [28]:
for i in kval :
    for j in cval:
        score = cross_val_score(SVC(C=j,kernel=i,gamma='scale'),X,y,cv=3)
        print(np.average(score))

0.96
0.9733333333333333
0.98
0.9933333333333333
0.9733333333333333
0.9666666666666667


In [30]:
for i in kval :
    for j in cval:
        score = cross_val_score(SVC(C=j,kernel=i,gamma='scale'),X,y,cv=3)
        print(i,"-",j,"-",np.average(score))

rbf - 1 - 0.96
rbf - 10 - 0.9733333333333333
rbf - 20 - 0.98
linear - 1 - 0.9933333333333333
linear - 10 - 0.9733333333333333
linear - 20 - 0.9666666666666667


In [31]:
from sklearn.model_selection import GridSearchCV

In [43]:
clf = GridSearchCV(SVC(gamma='scale'),{'kernel': ['rbf','linear','poly'],'C':[1,10,20]},cv=3)

In [44]:
clf

GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear', 'poly']})

In [45]:
clf.fit(X_train,y_train)

GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear', 'poly']})

In [46]:
clf.cv_results_

{'mean_fit_time': array([0.00560212, 0.00210468, 0.00597374, 0.00362953, 0.00211795,
        0.00231401, 0.00304198, 0.00394305, 0.00155632]),
 'std_fit_time': array([0.00250572, 0.00297647, 0.0022933 , 0.00256929, 0.0016653 ,
        0.00164994, 0.00271542, 0.003511  , 0.00220096]),
 'mean_score_time': array([0.01407719, 0.00489028, 0.00076683, 0.0063506 , 0.00437164,
        0.00303888, 0.00337187, 0.00376995, 0.00287374]),
 'std_score_time': array([0.00091025, 0.0030875 , 0.00108447, 0.00216548, 0.00388025,
        0.00361355, 0.00317137, 0.00319052, 0.00336094]),
 'param_C': masked_array(data=[1, 1, 1, 10, 10, 10, 20, 20, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'poly', 'rbf', 'linear', 'poly',
                    'rbf', 'linear', 'poly'],
              mask=[False, False, False, False, False, False, False, Fals

In [47]:
clf.fit(X,y)

GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear', 'poly']})

In [48]:
clf.cv_results_

{'mean_fit_time': array([0.00968456, 0.00461014, 0.00460752, 0.00455912, 0.0037082 ,
        0.00465131, 0.00487502, 0.00336027, 0.00336305]),
 'std_fit_time': array([0.00451148, 0.00420237, 0.00043899, 0.00322459, 0.00265606,
        0.00289575, 0.00310775, 0.00475214, 0.0034824 ]),
 'mean_score_time': array([0.00504835, 0.005831  , 0.00077899, 0.00295623, 0.00384521,
        0.00070516, 0.00169086, 0.00334255, 0.00309976]),
 'std_score_time': array([0.00094706, 0.00254838, 0.00056819, 0.00228725, 0.00324069,
        0.00099725, 0.00239124, 0.00472708, 0.00438372]),
 'param_C': masked_array(data=[1, 1, 1, 10, 10, 10, 20, 20, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'poly', 'rbf', 'linear', 'poly',
                    'rbf', 'linear', 'poly'],
              mask=[False, False, False, False, False, False, False, Fals

In [49]:
final = pd.DataFrame(clf.cv_results_)
final

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.009685      0.004511         0.005048        0.000947       1   
1       0.004610      0.004202         0.005831        0.002548       1   
2       0.004608      0.000439         0.000779        0.000568       1   
3       0.004559      0.003225         0.002956        0.002287      10   
4       0.003708      0.002656         0.003845        0.003241      10   
5       0.004651      0.002896         0.000705        0.000997      10   
6       0.004875      0.003108         0.001691        0.002391      20   
7       0.003360      0.004752         0.003343        0.004727      20   
8       0.003363      0.003482         0.003100        0.004384      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}               0.96   
1       linear   {'C': 1, 'kernel': 'linear'}               1.00   
2         poly     {'C': 1, 'kernel': 'poly'}               0.98   
3          rbf     {'C': 10, 'kernel': 'rbf'}               0.98   
4       linear  {'C': 10, 'kernel': 'linear'}               1.00   
5         poly    {'C': 10, 'kernel': 'poly'}               1.00   
6          rbf     {'C': 20, 'kernel': 'rbf'}               0.98   
7       linear  {'C': 20, 'kernel': 'linear'}               1.00   
8         poly    {'C': 20, 'kernel': 'poly'}               1.00   

   split1_test_score  split2_test_score  mean_test_score  std_test_score  \
0               0.98               0.94         0.960000        0.016330   
1               1.00               0.98         0.993333        0.009428   
2               0.94               0.98         0.966667        0.018856   
3               1.00               0.94         0.973333        0.024944   
4               0.94               0.98         0.973333        0.024944   
5               0.92               0.96         0.960000        0.032660   
6               0.98               0.98         0.980000        0.000000   
7               0.94               0.96         0.966667        0.024944   
8               0.92               0.96         0.960000        0.032660   

   rank_test_score  
0                7  
1                1  
2                5  
3                3  
4                3  
5                7  
6                2  
7                5  
8                7

In [50]:
final[['params','mean_test_score','rank_test_score']]

params  mean_test_score  rank_test_score
0      {'C': 1, 'kernel': 'rbf'}         0.960000                7
1   {'C': 1, 'kernel': 'linear'}         0.993333                1
2     {'C': 1, 'kernel': 'poly'}         0.966667                5
3     {'C': 10, 'kernel': 'rbf'}         0.973333                3
4  {'C': 10, 'kernel': 'linear'}         0.973333                3
5    {'C': 10, 'kernel': 'poly'}         0.960000                7
6     {'C': 20, 'kernel': 'rbf'}         0.980000                2
7  {'C': 20, 'kernel': 'linear'}         0.966667                5
8    {'C': 20, 'kernel': 'poly'}         0.960000                7

In [51]:
from sklearn.model_selection import RandomizedSearchCV

In [52]:
clf = RandomizedSearchCV(SVC(gamma='scale'),{'kernel': ['rbf','linear','poly'],'C':[1,10,20]},cv=3,n_iter=3)

In [53]:
clf

RandomizedSearchCV(cv=3, estimator=SVC(), n_iter=3,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear', 'poly']})

In [54]:
clf.fit(X,y)

RandomizedSearchCV(cv=3, estimator=SVC(), n_iter=3,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear', 'poly']})

In [55]:
clf.cv_results_

{'mean_fit_time': array([0.00527906, 0.00334048, 0.00507156]),
 'std_fit_time': array([0.00293083, 0.00309728, 0.00151008]),
 'mean_score_time': array([0.00383894, 0.01225924, 0.00331791]),
 'std_score_time': array([0.00298125, 0.00462272, 0.00075631]),
 'param_kernel': masked_array(data=['linear', 'rbf', 'poly'],
              mask=[False, False, False],
        fill_value='?',
             dtype=object),
 'param_C': masked_array(data=[1, 20, 20],
              mask=[False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'kernel': 'linear', 'C': 1},
  {'kernel': 'rbf', 'C': 20},
  {'kernel': 'poly', 'C': 20}],
 'split0_test_score': array([1.  , 0.98, 1.  ]),
 'split1_test_score': array([1.  , 0.98, 0.92]),
 'split2_test_score': array([0.98, 0.98, 0.96]),
 'mean_test_score': array([0.99333333, 0.98      , 0.96      ]),
 'std_test_score': array([0.00942809, 0.        , 0.03265986]),
 'rank_test_score': array([1, 2, 3])}

In [56]:
final1 = pd.DataFrame(clf.cv_results_)
final1

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.005279      0.002931         0.003839        0.002981       linear   
1       0.003340      0.003097         0.012259        0.004623          rbf   
2       0.005072      0.001510         0.003318        0.000756         poly   

  param_C                        params  split0_test_score  split1_test_score  \
0       1  {'kernel': 'linear', 'C': 1}               1.00               1.00   
1      20    {'kernel': 'rbf', 'C': 20}               0.98               0.98   
2      20   {'kernel': 'poly', 'C': 20}               1.00               0.92   

   split2_test_score  mean_test_score  std_test_score  rank_test_score  
0               0.98         0.993333        0.009428                1  
1               0.98         0.980000        0.000000                2  
2               0.96         0.960000        0.032660                3